version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile untuk aplikasi Flask
    container_name: flask_app
    ports:
      - "5000:5000"

  prometheus:
    build:
      context: ./monitoring
      dockerfile: Dockerfile  # Dockerfile untuk Prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - flask_app  # Pastikan Flask berjalan sebelum Prometheus
